package com.project.eloms.types;

public enum MessageType {

    //DEPARTMENT
    DEPARTMENT_SUCCESSFULLY_FETCHED,DEPARTMENT_NOT_EXIST, DEPARTMENT_SUCCESSFULLY_DELETED, DEPARTMENT_SUCCESSFULLY_CREATED,

    SUCCESSFULLY_FETCHED_DATA,
    ROLE_SUCCESSFULLY_CREATED, INVALID_PHONE_NUMBER, SUCCESSFULLY_SAVED, ROLE_NOT_EXIST, ACCOUNT_NOT_FOUND, ACCOUNT_SUCCESSFULLY_FETCHED, SUCCESSFULLY_FETCHED_ACCOUNTS, MISSING_REQUIRED_FIELD_INPUT, DTO_IS_NULL, DEPARTMENT_ALREADY_EXIST, MISSING_REQUIRED_INPUT, USERNAME_ALREADY_EXIST, ACCOUNT_UPDATED_SUCCESSFULLY, USERNAME_INPUT_REQUIRED, PHONE_NUMBER_MUST_BE_UNIQUE, ACCOUNT_SUCCESSFULLY_DELETED, LEAVE_TYPE_ALREADY_EXIST, LEAVE_SUCCESSFULLY_DELETED, LEAVE_NOT_EXIST, DEPARTMENT_NOT_FOUND
}
