package com.project.eloms.types;

public enum MessageType {
    DEPARTMENT_SUCCESSFULLY_FETCHED,
    DEPARTMENT_SUCCESSFULLY_DELETED,
    DEPARTMENT_SUCCESSFULLY_CREATED,
    SUCCESSFULLY_FETCHED_DATA,
    ROLE_SUCCESSFULLY_CREATED, INVALID_PHONE_NUMBER, DEPARTMENT_NOT_EXIST, SUCCESSFULLY_SAVED, ROLE_NOT_EXIST, ACCOUNT_NOT_FOUND, ACCOUNT_SUCCESSFULLY_FETCHED, SUCCESSFULLY_FETCHED_ACCOUNTS, MISSING_REQUIRED_FIELD_INPUT, DEPARTMENT_NOT_FOUND
}
